import type { Project } from '@/app/project-gallery';

export const projects:Project[] = [
  {
    id:'rabi', name:'RABI CLO', category:'Айдентика · Бренд одежды',
    description:'Логотип, символ и визуальная система бренда одежды. В знаке соединяются буква R, игла и нить. Тёплая природная палитра и тонкая графика продолжаются на тканевых этикетках, в лукбуке, упаковке и оформлении пространства.',
    cover:'/projects/rabi/01.png', coverAlt:'Мешочек и фирменная карточка RABI CLO',
    images:[
      {src:'/projects/rabi/01.png',alt:'Мешочек, льняная одежда и фирменная карточка RABI CLO'},
      {src:'/projects/rabi/02.png',alt:'Фирменная тканевая этикетка RABI CLO'},
      {src:'/projects/rabi/03.png',alt:'Фирменный символ: буква R, игла и нить'},
      {src:'/projects/rabi/04.jpeg',alt:'Природная цветовая палитра RABI CLO'},
      {src:'/projects/rabi/05.png',alt:'Тактильное тиснение фирменного символа'},
      {src:'/projects/rabi/06.png',alt:'Разворот лукбука RABI CLO'},
      {src:'/projects/rabi/07.png',alt:'Льняное платье RABI CLO'},
      {src:'/projects/rabi/08.png',alt:'Фирменный символ на деревянной вешалке'},
      {src:'/projects/rabi/09.png',alt:'Гравировка символа на металлической застёжке'},
      {src:'/projects/rabi/10.png',alt:'Фирменный буклет RABI CLO'},
      {src:'/projects/rabi/11.png',alt:'Подарочная упаковка с полупрозрачной обечайкой'},
      {src:'/projects/rabi/12.png',alt:'Фисташковая подарочная коробка RABI CLO'},
      {src:'/projects/rabi/13.png',alt:'Фирменный постер в витрине'},
      {src:'/projects/rabi/14.png',alt:'Фирменный символ на стеклянной двери'},
    ],
  },
  {
    id:'ahada',name:'AHADA',category:'Визуальная айдентика',
    description:'Продюсерская компания брендов',
    statement:'За каждым брендом — AHADA',
    cover:'/projects/ahada/01-office.png',coverAlt:'Вход в офис AHADA — символ на бордовой стене',
    images:[
      {src:'/projects/ahada/01-office.png',alt:'Вход в офис AHADA — символ на бордовой стене'},
      {src:'/projects/ahada/02-emboss.png',alt:'Тиснение символа AHADA на молочной бумаге'},
      {src:'/projects/ahada/03-folder.png',alt:'Фирменная папка AHADA'},
      {src:'/projects/ahada/04-book.jpeg',alt:'За каждым брендом — AHADA: идея, система, запуск'},
      {src:'/projects/ahada/05-card.png',alt:'Фирменная карточка и бордовый конверт'},
      {src:'/projects/ahada/06-box.jpeg',alt:'Бордовая коробка AHADA'},
      {src:'/projects/ahada/07-scarf.png',alt:'Платок с фирменным паттерном AHADA'},
      {src:'/projects/ahada/08-label.png',alt:'Фирменные этикетки AHADA'},
      {src:'/projects/ahada/09-detail.png',alt:'Рельеф символа AHADA на бордовом материале'},
    ],
  },
  {
    id:'alasr',name:'ZSH / AL’ASR',category:'АЙДЕНТИКА · МУЖСКОЕ АТЕЛЬЕ',
    description:'Визуальная айдентика мужского ателье ZSH / AL’ASR. Типографика, фирменная графика и паттерн формируют единую систему — от бирок и полиграфии до упаковки и оформления пространства. Шоколадные и молочные оттенки, фактуры ткани и бумаги раскрывают характер ателье через материалы и детали.',
    cover:'/projects/alasr/06-shirt.png',coverAlt:'Белая рубашка с шоколадной обечайкой ZSH / AL’ASR',
    images:[
      {src:'/projects/alasr/06-shirt.png',alt:'Белая рубашка с шоколадной обечайкой ZSH / AL’ASR'},
      {src:'/projects/alasr/01-suit.png',alt:'Костюм и молочная рубашка ZSH / AL’ASR'},
      {src:'/projects/alasr/02-wordmark.png',alt:'Типографическая композиция ZSH / AL’ASR'},
      {src:'/projects/alasr/03-pattern.png',alt:'Фирменный паттерн ZSH / AL’ASR'},
      {src:'/projects/alasr/04-stationery.png',alt:'Молочная папка с тиснением и фирменная полиграфия'},
      {src:'/projects/alasr/05-tailoring.png',alt:'Фирменная графика на лекалах мужского ателье'},
      {src:'/projects/alasr/07-label.png',alt:'Фирменная этикетка на подкладке пиджака'},
      {src:'/projects/alasr/08-swatches.png',alt:'Каталог образцов тканей ZSH / AL’ASR'},
      {src:'/projects/alasr/09-box.png',alt:'Фирменная коробка с костюмом'},
    ],
  },
  {
    id:'desert-rose',name:'Desert Rose',category:'Brand Identity / Coffee Shop',
    description:'Визуальная айдентика кофейни: логотип и монограмма, типографика, цветовая палитра, упаковка и оформление пространства.',
    cover:'/projects/desert-rose/09-coffee.jpg',coverAlt:'Стакан Desert Rose под кофемашиной',
    images:[
      {src:'/projects/desert-rose/01-cover.jpg',alt:'Desert Rose — обложка проекта'},
      {src:'/projects/desert-rose/02-main-logo.jpg',alt:'Основной логотип Desert Rose с розой'},
      {src:'/projects/desert-rose/03-secondary-logo.jpg',alt:'Монограмма DR — вторичный логотип'},
      {src:'/projects/desert-rose/04-typography.jpg',alt:'Типографика Desert Rose'},
      {src:'/projects/desert-rose/05-color-palette.jpg',alt:'Цветовая палитра Desert Rose'},
      {src:'/projects/desert-rose/06-facade.jpg',alt:'Фасад кофейни Desert Rose'},
      {src:'/projects/desert-rose/07-bag.jpg',alt:'Фирменный пакет Desert Rose'},
      {src:'/projects/desert-rose/08-cup-carrier.jpg',alt:'Стаканы и переноска Desert Rose'},
      {src:'/projects/desert-rose/09-coffee.jpg',alt:'Фирменный стакан для кофе'},
      {src:'/projects/desert-rose/10-menu-interior.jpg',alt:'Меню Desert Rose в интерьере кофейни'},
    ],
  },
  {
    id:'emikam',name:'EMIKAM',category:'Айдентика · Медицинская одежда',
    description:'Айдентика бренда медицинской одежды. Авторская монограмма EK соединяет строгую типографику с пластичными линиями. Бордовый, ледяной голубой, молочный и хром формируют визуальную систему: от ткани и вышивки до этикетки и упаковки. Предметные визуализации раскрывают концепцию бренда через материалы, свет и детали.',
    cover:'/projects/emikam/01-box-cover.jpeg',coverAlt:'EMIKAM — молочная коробка с бордовой бумагой и печатью',
    images:[
      {src:'/projects/emikam/01-box-cover.jpeg',alt:'EMIKAM — молочная коробка с бордовой бумагой и печатью'},
      {src:'/projects/emikam/02-uniform.png',alt:'Голубой медицинский костюм на рейле'},
      {src:'/projects/emikam/03-folded-uniform.webp',alt:'Сложенная голубая форма с бордовой биркой'},
      {src:'/projects/emikam/04-stationery.jpg',alt:'Голубая карточка, бордовая бирка и молочная карточка с тиснением'},
      {src:'/projects/emikam/05-bag.png',alt:'Бордовый фирменный пакет EMIKAM'},
      {src:'/projects/emikam/06-box.png',alt:'Молочная коробка с бордовой бумагой, паттерном и круглой печатью'},
      {src:'/projects/emikam/07-garment-cover.jpg',alt:'Молочный чехол с бордовыми брюками'},
      {src:'/projects/emikam/08-embroidery.png',alt:'Вышивка монограммы на бордовой ткани крупным планом'},
    ],
  },
];
